services:
  crypthora-chat:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
  postgres:
    ports:
      - "5432:5432"
  ntfy:
    ports:
      - "8181:80"
