name: Security issue report
description: Create a report for a security issue or vulnerability
labels: ["security"]
body:
    - type: dropdown
      id: type
      attributes:
          label: Is the issue/vulnerability in
          options:
              - Frontend Client Code
              - Backend Server Code
              - Don't know
      validations:
          required: true
    - type: textarea
      id: description
      attributes:
          label: Describe the issue/vulnerability
          placeholder: "A clear and concise description of what the issue or vulnerability is."
      validations:
          required: true
    - type: textarea
      id: additional
      attributes:
          label: Additional context or ideas for a fix
          placeholder: Add any ideas for a fix or other context or screenshots about the problem here.