/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconFaSolidSlash: typeof import('~icons/fa-solid/slash').default
  const IconIcRoundSend: typeof import('~icons/ic/round-send').default
  const IconMaterialSymbolsArrowBackRounded: typeof import('~icons/material-symbols/arrow-back-rounded').default
  const IconMaterialSymbolsDeleteOutlineRounded: typeof import('~icons/material-symbols/delete-outline-rounded').default
  const IconMaterialSymbolsEditOutlineRounded: typeof import('~icons/material-symbols/edit-outline-rounded').default
  const IconMaterialSymbolsInfoOutlineRounded: typeof import('~icons/material-symbols/info-outline-rounded').default
  const IconMaterialSymbolsLightBackgroundReplaceRounded: typeof import('~icons/material-symbols-light/background-replace-rounded').default
  const IconMaterialSymbolsReplyRounded: typeof import('~icons/material-symbols/reply-rounded').default
  const IconMdiAccountAlertOutline: typeof import('~icons/mdi/account-alert-outline').default
  const IconMdiAccountArrowLeftOutline: typeof import('~icons/mdi/account-arrow-left-outline').default
  const IconMdiAccountGroup: typeof import('~icons/mdi/account-group').default
  const IconMdiAccountMultipleAddOutline: typeof import('~icons/mdi/account-multiple-add-outline').default
  const IconMdiArrowDown: typeof import('~icons/mdi/arrow-down').default
  const IconMdiAttachFile: typeof import('~icons/mdi/attach-file').default
  const IconMdiCheckBold: typeof import('~icons/mdi/check-bold').default
  const IconMdiCheckCircleOutline: typeof import('~icons/mdi/check-circle-outline').default
  const IconMdiChevronLeft: typeof import('~icons/mdi/chevron-left').default
  const IconMdiChevronRight: typeof import('~icons/mdi/chevron-right').default
  const IconMdiClose: typeof import('~icons/mdi/close').default
  const IconMdiColor: typeof import('~icons/mdi/color').default
  const IconMdiContentCopy: typeof import('~icons/mdi/content-copy').default
  const IconMdiDelete: typeof import('~icons/mdi/delete').default
  const IconMdiDeleteForever: typeof import('~icons/mdi/delete-forever').default
  const IconMdiDownload: typeof import('~icons/mdi/download').default
  const IconMdiEditOutline: typeof import('~icons/mdi/edit-outline').default
  const IconMdiEyeOffOutline: typeof import('~icons/mdi/eye-off-outline').default
  const IconMdiEyeOutline: typeof import('~icons/mdi/eye-outline').default
  const IconMdiFileDocumentErrorOutline: typeof import('~icons/mdi/file-document-error-outline').default
  const IconMdiFormatText: typeof import('~icons/mdi/format-text').default
  const IconMdiFullscreen: typeof import('~icons/mdi/fullscreen').default
  const IconMdiFullscreenExit: typeof import('~icons/mdi/fullscreen-exit').default
  const IconMdiGear: typeof import('~icons/mdi/gear').default
  const IconMdiImageEditOutline: typeof import('~icons/mdi/image-edit-outline').default
  const IconMdiImagePlus: typeof import('~icons/mdi/image-plus').default
  const IconMdiImport: typeof import('~icons/mdi/import').default
  const IconMdiImportantDevices: typeof import('~icons/mdi/important-devices').default
  const IconMdiInformationOutline: typeof import('~icons/mdi/information-outline').default
  const IconMdiLock: typeof import('~icons/mdi/lock').default
  const IconMdiLockOpenVariant: typeof import('~icons/mdi/lock-open-variant').default
  const IconMdiMinus: typeof import('~icons/mdi/minus').default
  const IconMdiMoreVert: typeof import('~icons/mdi/more-vert').default
  const IconMdiOpenInApp: typeof import('~icons/mdi/open-in-app').default
  const IconMdiPause: typeof import('~icons/mdi/pause').default
  const IconMdiPlay: typeof import('~icons/mdi/play').default
  const IconMdiPlus: typeof import('~icons/mdi/plus').default
  const IconMdiPlusThick: typeof import('~icons/mdi/plus-thick').default
  const IconMdiRotateClockwise: typeof import('~icons/mdi/rotate-clockwise').default
  const IconMdiShieldLock: typeof import('~icons/mdi/shield-lock').default
  const IconMdiShimmerOutline: typeof import('~icons/mdi/shimmer-outline').default
  const IconMdiStar: typeof import('~icons/mdi/star').default
  const IconMdiStarOutline: typeof import('~icons/mdi/star-outline').default
  const IconMdiStickerEmoji: typeof import('~icons/mdi/sticker-emoji').default
  const IconMdiStickerPlusOutline: typeof import('~icons/mdi/sticker-plus-outline').default
  const IconMdiStorage: typeof import('~icons/mdi/storage').default
  const IconMdiTrayDownload: typeof import('~icons/mdi/tray-download').default
  const IconMdiUserRemoveOutline: typeof import('~icons/mdi/user-remove-outline').default
  const IconMdiVolumeHigh: typeof import('~icons/mdi/volume-high').default
  const IconMdiVolumeLow: typeof import('~icons/mdi/volume-low').default
  const IconMdiVolumeMedium: typeof import('~icons/mdi/volume-medium').default
  const IconMdiVolumeMute: typeof import('~icons/mdi/volume-mute').default
  const IconProiconsEmoji: typeof import('~icons/proicons/emoji').default
}
